using Albatross.CodeGen;
using Albatross.CodeGen.Database;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Albatross.CodeGen.SqlServer {
	[CodeGenerator("declare statement", "sql", Category ="Sql Server", Description = "Create a declare statement based on the parameters generated by the children")]
	public class DeclareStatement : ICodeGenerator<DatabaseObject, SqlQueryOption>{

		IColumnSqlTypeBuilder _typeBuilder;

		public DeclareStatement(IColumnSqlTypeBuilder typeBuilder) {
			_typeBuilder = typeBuilder;
		}

		public string Name => "declare statement";
		public string Category => "Sql server";
		public string Description => "Create a declare statement based on the parameters generated by the children";
		public string Target => "sql";

		public Type SourceType => typeof(DatabaseObject);
		public Type OptionType => typeof(SqlQueryOption);

		public IEnumerable<ICodeGenerator<DatabaseObject, SqlQueryOption>> Children { get; set; }

		public StringBuilder Build(StringBuilder sb, DatabaseObject list, SqlQueryOption options, ICodeGeneratorFactory factory) {
			sb.AppendLine("declare");


			return sb;
		}

		public StringBuilder Build(StringBuilder sb, DatabaseObject t, SqlQueryOption option, IEnumerable<ICodeGenerator<DatabaseObject, SqlQueryOption>> children, ICodeGeneratorFactory factory) {
			throw new NotImplementedException();
		}

		public StringBuilder Build(StringBuilder sb, object t, object options, ICodeGeneratorFactory factory) {
			throw new NotImplementedException();
		}
	}
}
