using Albatross.CodeGen;
using Albatross.CodeGen.Database;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Albatross.CodeGen.SqlServer {
	[CodeGenerator("declare statement", "sql", Category ="Sql Server", Description = "Create a declare statement based on the parameters generated by the children")]
	public class DeclareStatement : ICodeGenerator<DatabaseObject, SqlQueryOption>{

		IColumnSqlTypeBuilder typeBuilder;
		IGetVariable getVariable;

		public DeclareStatement(IColumnSqlTypeBuilder typeBuilder, IGetVariable getVariable) {
			this.typeBuilder = typeBuilder;
			this.getVariable = getVariable;
		}

		public string Name => "declare statement";
		public string Category => "Sql server";
		public string Description => "Create a declare statement based on the parameters generated by the children";
		public string Target => "sql";

		public Type SourceType => typeof(DatabaseObject);
		public Type OptionType => typeof(SqlQueryOption);

		public event Func<StringBuilder, DatabaseObject, SqlQueryOption, ICodeGeneratorFactory, IEnumerable<object>> Yield;

		public StringBuilder Build(StringBuilder sb, DatabaseObject src, SqlQueryOption options, ICodeGeneratorFactory factory, out IEnumerable<object> used) {
			List<object> list = new List<object>();
			list.Add(this);

			sb.AppendLine("declare");

			StringBuilder child = new StringBuilder();
			var items = Yield(child, src, options, factory);
			foreach (var item in items) {
				foreach (var pair in getVariable.Get(item)) {
					sb.Tab().Append(pair.Key).Append(" as ").Append(pair.Value).Comma().AppendLine();
				}
			}
			sb.Append(child);
			list.AddRange(items);
			used = list;
			return sb;
		}
	}
}
